###
GET http://127.0.0.1:3000/api/v1/questions

###
delete http://127.0.0.1:3000/api/v1/questions/10



###
POST http://127.0.0.1:3000/api/v1/questions
Content-Type: application/json

{
   "title":"How works Machine Learning",
   "tag": "DataSciece"   
}
